parameters:
#    mysn_user.example.class: Mysn\UserBundle\Example

services:
#    mysn_user.example:
#        class: %mysn_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
