<?php

namespace Mysn\Bundle\InterfaceBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ARTICLESRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ARTICLESRepository extends EntityRepository
{
}