<?php

namespace Mysn\Bundle\InterfaceBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * USERSRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class USERSRepository extends EntityRepository
{
}